### ISSUE TITLE
[Bug] ... 1.16.5 Latest Additional Lanterns Spams Advancesment.recipes text

### ISSUE THREAD

**Issue by ModernGamingWorld** [SuperMartijn642/AdditionalLanterns#12] opened 2023-01-04 05:19 UTC
**Version Info**
- Minecraft, 1.16.5
- Additional Lantern, 1.0.2-forge-mc1.16
- SuperMartijn642's Core lib, 1.1.0a-forge-mc1.16

**Description of the Bug**
As soon as I join a world with the updated version on my custom pack the said issue appears in the screenshot

**Steps to Reproduce**
...

**Screenshots**
...
![2023-01-03_23 16 43](https://user-images.githubusercontent.com/75923060/210489327-601a2c2c-4ac5-4cbe-916b-87e926d62161.png)

**Comment by SuperMartijn642** [comment] 2023-01-04 14:40
I cannot reproduce the issue. I can go into a world with only Additional Lanterns and the two dependencies installed and there's no spam in the chat nor in the logs.

Could you narrow down which other mods are needed to reproduce this?

**Comment by ModernGamingWorld** [comment] 2023-01-06 01:14
@SuperMartijn642 I Can't fully Narrow it down to what other mods could be causing this, as I have over 420ish mods in my custom modpack, I can't remove mods without breaking something within the pack

**Comment by SuperMartijn642** [comment] 2023-01-07 20:25
As this problem seems to be something related to your modpack and doesn't occur with just Additional Lanterns, I will close the issue.
Let me know if this does turn out to be an issue with Additional Lanterns.

**Closed as completed by SuperMartijn642** 2023-01-07 20:25 UTC
Labels: bug

**Comment by a-molokodrengo** [comment] 2023-03-03 21:02
I has also having this issue with additional lanterns versions 1.0.3 & 1.0.4 for minecraft 1.18.2 in my modpack.  Disabling Clickable Advancements solved it for me (clickadv-1.18.2-2.5.jar), hope this helps
